### ISSUE TITLE
Reason for using node-gyp?

### ISSUE THREAD

**Issue by webketje** [websockets/utf-8-validate#103] opened 2022-02-15 20:56 UTC
Hi there,

Is there any reason why the module defaults to `validation.c` (compiled with node-gyp postinstall)
AFAICS the "fallback" contains the same "main" code and no important native API's are used.
Is it purely for efficiency with large files?

Context: looking for replacement for https://github.com/wayfind/is-utf8 for [Metalsmith SSG](https://metalsmith.io), due to erroneous handling of ASCII chars, see https://github.com/wayfind/is-utf8/issues/6 but cannot consider any lib that requires node-gyp (due to platform-specific issues)

So this request would be to justify node-gyp dependency overhead in the docs and/ or make it an optionalDependency (as `require('utf8-validate/fallback')` should also work

**Comment by lpinca** [comment] 2022-02-16 06:03
Because the native version is a lot faster.

**Comment by lpinca** [comment] 2022-02-16 06:30
FWIW, prebuilt binaries are included in the npm package for the most common platforms (Linux x64, Windows ia32 & x64, macOS x64, arm64) so node-gyp is not used in most cases.

**Comment by webketje** [comment] 2022-02-16 08:10
@lpinca oh ok, that wasn't obvious from looking through the README/ sources

**Comment by lpinca** [comment] 2022-02-16 11:18
I think it is obvious if you look at the module entry point and package.json but feel free to open a PR.

**Comment by lpinca** [comment] 2022-02-17 15:53
> Interesting to note and what was consistent across multiple runs, is that when run on a relatively large binary file (eg .jpg, .zip), native utf-8-validate (precompiled) was up to 10x slower than "fallback", and both were outperformed by is-utf8.

In this case the few bytes are probably not valid UTF-8, so the cost of switching from JS to the native code does not pay off. This is confirmed by the fact that there is no difference between the 5MB and 12MB file.

See https://github.com/websockets/ws/pull/1348. See also https://github.com/websockets/utf-8-validate/pull/101.

**Comment by lpinca** [comment] 2022-02-25 17:29
I'm closing this as answered. Discussion can continue if needed.

**Closed by lpinca** 2022-02-25 17:29 UTC
